import "../styles/globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import NextAuthSessionProvider from "./provider/sessionProvider";
import { ThemeProvider } from "next-themes";

const inter = Lato({ weight: ["900", "400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "odoo 2025",
  description: "Generated by ayush",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
